# Generated by Django 6.0.6 on 2026-06-03 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_evenement', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('type_evenement', models.CharField(choices=[('CHANGEMENT_STATUT', 'Changement de statut'), ('ALARME', 'Alarme'), ('MAINTENANCE', 'Maintenance'), ('AUTRE', 'Autre')], default='AUTRE', max_length=50)),
                ('antenne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='api.antenne')),
            ],
        ),
        migrations.CreateModel(
            name='Interconnexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_liaison', models.CharField(max_length=100)),
                ('bande_passante', models.CharField(max_length=100)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('EN_MAINTENANCE', 'En maintenance')], default='ACTIF', max_length=20)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connexions_entrantes', to='api.antenne')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connexions_sortantes', to='api.antenne')),
            ],
        ),
        migrations.CreateModel(
            name='JournalActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, null=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journaux', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
