# Generated by Django 6.0.4 on 2026-06-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_historique_interconnexion_journalactivite'),
    ]

    operations = [
        migrations.AddField(
            model_name='antenne',
            name='azimuth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='antenne',
            name='downtilt',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='antenne',
            name='polarisation',
            field=models.CharField(default='Verticale', max_length=50),
        ),
        migrations.AddField(
            model_name='antenne',
            name='puissance_tx',
            field=models.FloatField(default=20.0),
        ),
        migrations.AddField(
            model_name='antenne',
            name='tilt',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
