# Generated by Django 6.0.4 on 2026-07-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_antenne_azimuth_antenne_downtilt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='antenne',
            name='diametre',
            field=models.FloatField(blank=True, help_text="Diamètre de l'antenne en mètres", null=True),
        ),
        migrations.AddField(
            model_name='antenne',
            name='type_configuration',
            field=models.CharField(default='1+0', help_text='Ex: 1+0, 1+1, 2+0', max_length=50),
        ),
    ]
